RIDE is a test data editor for `Robot Framework`__ test data. The latest releases are available from the `download page`__ on Google Code.

  * Please read the [[Installation Instructions]] to get smoothly started.
  * [[Release Notes]] contains the list of enhancements/bug fixes per
    release.
  * [[How To]] contains a list of useful tips for more efficient RIDE
    usage. [[Keyword Completion]] is one of the most powerful RIDE features.
  * Tests can also be executed straight from RIDE via [[Test Runner Plugin]].
  * There are also some handy [[Keyboard Shortcuts]].
  * Sometimes, there's a need to tweak how RIDE works, this is described in
    [[Settings]] page.

RIDE `issue tracker`__ is on Google Code.

__ http://robotframework.org
__ http://code.google.com/p/robotframework-ride/downloads/list
__ http://code.google.com/p/robotframework-ride/issues/list