=======
Plugins
=======

Introduction
============

RIDE allows adding additional functionality via plugins. Several plugins are included in the basic installation, and additional plugins may be available from other sources.

Managing Plugins
================

Selecting `Tools|Manage Plugins` from main menu opens a Plugin manager. The
available plugins are listed, and there's a possibility to activate/deactivate
them.

Installing Plugins
------------------

See "Finding Plugins" in the `Plugin API documentation`__.

__ https://github.com/robotframework/RIDE/blob/master/src/robotide/pluginapi/__init__.py