=============
Release notes
=============

.. contents::
  :local:
  :depth: 1

The latest releases are available from the `download page`__. Older release notes are [[archived|Old Release Notes]] on a separate page.

RIDE 0.43
=========

============ ============= ======== ==================================================================================================
     ID           Type     Priority                                              Summary                                              
============ ============= ======== ==================================================================================================
`Issue 861`_ Enhancement   High     UI for editing RIDE's settings                                                                    
`Issue 157`_ Defect        Medium   RIDE should not allow editing read-only files                                                     
`Issue 442`_ Defect        Medium   Help-About isn't available on OSX                                                                 
`Issue 781`_ Defect        Medium   Help-Release Notes not available on Mac OSX after first launch                                    
`Issue 895`_ Defect        Medium   The pythonpath setting is not used by Run plugin                                                  
`Issue 943`_ Defect        Medium   Copy does not work in the output view of Run tab                                                  
`Issue 945`_ Defect        Medium   Can't run test from RIDE due to assci issue                                                       
`Issue 952`_ Defect        Medium   RIDE should survive if configuration file is corrupted                                            
`Issue 623`_ Enhancement   Medium   Check for updates once a week                                                                     
`Issue 871`_ Enhancement   Medium   Create variable keyboard shortcut                                                                 
`Issue 927`_ Enhancement   Medium   Default space number should be cofigurable                                                        
`Issue 932`_ Enhancement   Medium   Mechanism for settings migration                                                                  
`Issue 934`_ Enhancement   Medium   Colorize Library keywords in a different color than User keywords                                 
`Issue 866`_ Documentation Medium   Document how to configure line separator                                                          
`Issue 940`_ Defect        Low      In ReleaseNote Tab, the first three Hyperlinks should refer to GitHub now, no longer to GoogleCode
============ ============= ======== ==================================================================================================

.. _Issue 861: http://code.google.com/p/robotframework-ride/issues/detail?id=861
.. _Issue 157: http://code.google.com/p/robotframework-ride/issues/detail?id=157
.. _Issue 442: http://code.google.com/p/robotframework-ride/issues/detail?id=442
.. _Issue 781: http://code.google.com/p/robotframework-ride/issues/detail?id=781
.. _Issue 895: http://code.google.com/p/robotframework-ride/issues/detail?id=895
.. _Issue 943: http://code.google.com/p/robotframework-ride/issues/detail?id=943
.. _Issue 945: http://code.google.com/p/robotframework-ride/issues/detail?id=945
.. _Issue 952: http://code.google.com/p/robotframework-ride/issues/detail?id=952
.. _Issue 623: http://code.google.com/p/robotframework-ride/issues/detail?id=623
.. _Issue 871: http://code.google.com/p/robotframework-ride/issues/detail?id=871
.. _Issue 927: http://code.google.com/p/robotframework-ride/issues/detail?id=927
.. _Issue 932: http://code.google.com/p/robotframework-ride/issues/detail?id=932
.. _Issue 934: http://code.google.com/p/robotframework-ride/issues/detail?id=934
.. _Issue 866: http://code.google.com/p/robotframework-ride/issues/detail?id=866
.. _Issue 940: http://code.google.com/p/robotframework-ride/issues/detail?id=940

Altogether 15 issues.


RIDE 0.42
=========

============ =========== ======== ==============================================================
     ID          Type    Priority                            Summary                            
============ =========== ======== ==============================================================
`Issue 917`_ Defect      High     Common Windows shorcuts don't work in Text Edit tab or Run tab
`Issue 939`_ Defect      High     No more possible to save TXT file from Ride when Backup fails 
`Issue 3`_   Enhancement High     Find unused User Keywords                                     
`Issue 926`_ Enhancement High     Ability to ignore a directory when loading data               
`Issue 911`_ Defect      Medium   Suffix of resource file disappears after rename               
`Issue 930`_ Defect      Medium   Library import with relative path doesn't work in RIDE 0.41   
`Issue 920`_ Enhancement Medium   Sorting of external resources                                 
`Issue 931`_ Enhancement Medium   Unknown variables should be colored differently from known    
`Issue 938`_ Enhancement Medium   "Report a Problem" option to Help menu                        
============ =========== ======== ==============================================================

.. _Issue 917: http://code.google.com/p/robotframework-ride/issues/detail?id=917
.. _Issue 939: http://code.google.com/p/robotframework-ride/issues/detail?id=939
.. _Issue 3: http://code.google.com/p/robotframework-ride/issues/detail?id=3
.. _Issue 926: http://code.google.com/p/robotframework-ride/issues/detail?id=926
.. _Issue 911: http://code.google.com/p/robotframework-ride/issues/detail?id=911
.. _Issue 930: http://code.google.com/p/robotframework-ride/issues/detail?id=930
.. _Issue 920: http://code.google.com/p/robotframework-ride/issues/detail?id=920
.. _Issue 931: http://code.google.com/p/robotframework-ride/issues/detail?id=931
.. _Issue 938: http://code.google.com/p/robotframework-ride/issues/detail?id=938

Altogether 9 issues.

RIDE 0.41
=========

A major problem in 64 bit Windows 7 where RIDE froze when Google Chrome is
running was fixed (`Issue 714`_). Also special thanks to Andreas Brain for contributing
Sorting of keywords (`Issue 624`_).

============ =========== ======== ======================================================
     ID          Type    Priority                        Summary
============ =========== ======== ======================================================
`Issue 714`_ Defect      High     RIDE sometimes hangs up while google chrome is running
`Issue 918`_ Defect      High     Errors thrown by RIDE 0.40.2 Test Runner
`Issue 924`_ Defect      High     Encoding error
`Issue 624`_ Enhancement Medium   Sorting of keywords
`Issue 882`_ Enhancement Medium   Remove support for serializing old style metadata
============ =========== ======== ======================================================

.. _Issue 714: http://code.google.com/p/robotframework-ride/issues/detail?id=714
.. _Issue 918: http://code.google.com/p/robotframework-ride/issues/detail?id=918
.. _Issue 924: http://code.google.com/p/robotframework-ride/issues/detail?id=924
.. _Issue 624: http://code.google.com/p/robotframework-ride/issues/detail?id=624
.. _Issue 882: http://code.google.com/p/robotframework-ride/issues/detail?id=882

Altogether 5 issues.


RIDE 0.40.1
===========

RIDE 0.40 unfortunately contained some pretty severe bugs, and RIDE 0.40.1 was released shortly after to fix these.
All the fixed bugs are listed in the below table:

============ =========== ======== ============================================================================================
     ID          Type    Priority                                           Summary
============ =========== ======== ============================================================================================
`Issue 907`_ Defect      Critical Unable to open ride.py if large quantity of tests in directories
`Issue 910`_ Enhancement High     Backup file when saving so that it can be restored if saving fails
`Issue 798`_ Defect      Medium   ProgressDialog_Pulse can't be initialized when running ride along with projects file opening
`Issue 909`_ Defect      Medium   "Hide All Test Cases" doesn't work
============ =========== ======== ============================================================================================

.. _Issue 907: http://code.google.com/p/robotframework-ride/issues/detail?id=907
.. _Issue 910: http://code.google.com/p/robotframework-ride/issues/detail?id=910
.. _Issue 798: http://code.google.com/p/robotframework-ride/issues/detail?id=798
.. _Issue 909: http://code.google.com/p/robotframework-ride/issues/detail?id=909

Altogether 4 issues.


RIDE 0.40
=========

There are two major improvements in the RIDE 0.40. First, a plain text editor was added to enable
editing whole file at a time (`issue 899`_). Second, it is now possible to write plain text files so
that columns are aligned according to headers (`issue 903`_). This supports writing data-driven tests
with RIDE more efficiently. In addition, files written in HTML and TSV formats are now cleaner.

Some other improvements and bug fixes are included, all of which are listed in the table below.


============ =========== ======== =============================================================================
     ID          Type    Priority                                    Summary
============ =========== ======== =============================================================================
`Issue 899`_ Defect      High     Renaming a dirty Test Suite, gets its file deleted
`Issue 903`_ Enhancement High     Improved data formatting when saving
`Issue 904`_ Enhancement High     Support for editing test data in plain text format
`Issue 735`_ Defect      Medium   Using # character to comment rows collapses the commented row on next startup
`Issue 876`_ Defect      Medium   Bug in testrunner plugin, module SocketListener.py
`Issue 892`_ Defect      Medium   RIDE cannot create a new top level suite file
`Issue 893`_ Defect      Medium   RIDE - Problems in multiuser environment due to hard-coded port no.
`Issue 897`_ Defect      Medium   HTML files are always written using unix line separators
`Issue 901`_ Enhancement Medium   Show table headers in grid editor
============ =========== ======== =============================================================================

.. _Issue 899: http://code.google.com/p/robotframework-ride/issues/detail?id=899
.. _Issue 903: http://code.google.com/p/robotframework-ride/issues/detail?id=903
.. _Issue 904: http://code.google.com/p/robotframework-ride/issues/detail?id=904
.. _Issue 735: http://code.google.com/p/robotframework-ride/issues/detail?id=735
.. _Issue 876: http://code.google.com/p/robotframework-ride/issues/detail?id=876
.. _Issue 892: http://code.google.com/p/robotframework-ride/issues/detail?id=892
.. _Issue 893: http://code.google.com/p/robotframework-ride/issues/detail?id=893
.. _Issue 897: http://code.google.com/p/robotframework-ride/issues/detail?id=897
.. _Issue 901: http://code.google.com/p/robotframework-ride/issues/detail?id=901

Altogether 9 issues.

__ https://github.com/robotframework/RIDE/downloads