========
Settings
========

Settings file
=============

Some persistent information about RIDE and [[Plugins]] is stored in a settings
file called `settings.cfg`. Its exact location depends on the operating system. On Windows the location is::

    %APPDATA%\RobotFramework\ride

and on Linux, it is::

    ~/.robotframework/ride

Modifying settings
==================

Most of the settings are designed so that they will either be automatically
updated or a GUI is offered for editing them.  However, there are currently
some settings that must be edited manually, for example the `default template`
setting used by [[Templates]].

A graphical settings managed is targeted for version 0.41.
