========
Settings
========

Settings file
=============

Some persistent information about RIDE and [[Plugins]] is stored in a settings
file called `settings.cfg`. Its exact location depends on the operating system. On Windows the location is::

    %APPDATA%\RobotFramework\ride

and on Linux, it is::

    ~/.robotframework/ride

Modifying settings
==================

Most of the settings are designed so that they will either be automatically
updated or a GUI is offered for editing them. However, some settings can only be changed by manually editing the settings file.

A graphical settings manager is targeted for version 0.41.
